version: "3.8"
services:
  goservice:
    build: "./Go"
    container_name: goservice
    restart: always
    ports:
      - "8080:8080"
    depends_on: 
      - rabbitmq
    networks: 
      - network

  flaskapp:
    build: "./Python"
    container_name: flaskapp
    restart: always
    volumes:
      - .:/opt/services/flaskapp/src
    ports: 
      - "80:80"
    depends_on: 
      - rabbitmq
    networks:
      - network

  # nginx:
  #   build: "./nginx"
  #   ports:
  #     - "8080:80"
  #   volumes:
  #     - ./conf.d:/etc/nginx/conf.d
  #   networks:
  #     - web_nw
  #   depends_on: 
  #     - flaskapp
  #     - goservice
      
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    volumes:
      - ./Rabbitmq/etc/definitions.json:/etc/rabbitmq/definitions.json
      - ./Rabbitmq/etc/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./Rabbitmq/data:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit
      - ./Rabbitmq/logs:/var/log/rabbitmq/log
    ports:
      - "4369:4369"
      - "5671:5671" 
      - "5672:5672" 
      - "15672:15672"
    networks: 
      - network
networks:
  network: {}
volumes:
  dbdata: