version: '2'
services:
  gogrpc:
    image: garyjoan14/gogrpc:1.0
    container_name: gogrpc
    restart: always
    ports:
      - "8081:8081"
  pythongrpc:
    image: garyjoan14/pythongrpc:1.0
    container_name: pythongrpc
    restart: always
    ports: 
      - "81:81"
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017

  redis:
    image: redis
    container_name: redis
    restart: always
    ports: 
      - 6379:6379
  

