apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-grpc
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gogrpc
  template:
    metadata:
      labels:
        app: gogrpc
    spec:
      containers:
      - image: garyjoan14/gogrpc:1.1
        name: go
        ports:
        - containerPort: 8081
      - image: garyjoan14/pythongrpc:1.4
        name: pythongrpc
        ports:
        - containerPort: 81
      - image: redis
        name: redis
        ports:
        - containerPort: 6379
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: gogrpc-svc
  namespace: project
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  selector:
    app: gogrpc
---
  apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    annotations:
      kubernetes.io/ingress.class: nginx
    name: nginx-ingress
    namespace: project
  spec:
    rules:
      - http:
            paths:
              - backend:
                  serviceName: gogrpc-svc
                  servicePort: 8081
                path: /


